// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Board struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   int64          `json:"created_at"`
}

type Card struct {
	ID          string         `json:"id"`
	ListID      string         `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullString `json:"assignee_id"`
	Position    int64          `json:"position"`
	Completed   sql.NullInt64  `json:"completed"`
	CreatedAt   int64          `json:"created_at"`
}

type CardTag struct {
	CardID string `json:"card_id"`
	TagID  string `json:"tag_id"`
}

type Comment struct {
	ID        string `json:"id"`
	CardID    string `json:"card_id"`
	UserID    string `json:"user_id"`
	Text      string `json:"text"`
	CreatedAt int64  `json:"created_at"`
}

type List struct {
	ID        string `json:"id"`
	BoardID   string `json:"board_id"`
	Title     string `json:"title"`
	Position  int64  `json:"position"`
	CreatedAt int64  `json:"created_at"`
}

type Tag struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Color     string `json:"color"`
	CreatedAt int64  `json:"created_at"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
