// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateBoard(ctx context.Context, arg CreateBoardParams) error
	CreateCard(ctx context.Context, arg CreateCardParams) error
	CreateCardTag(ctx context.Context, arg CreateCardTagParams) error
	CreateComment(ctx context.Context, arg CreateCommentParams) error
	CreateList(ctx context.Context, arg CreateListParams) error
	DeleteCard(ctx context.Context, id string) error
	DeleteCardTags(ctx context.Context, cardID string) error
	GetBoard(ctx context.Context, id string) (GetBoardRow, error)
	GetBoards(ctx context.Context) ([]GetBoardsRow, error)
	GetCardsByListIds(ctx context.Context, listIds []string) ([]GetCardsByListIdsRow, error)
	GetCommentsByCardIds(ctx context.Context, cardIds []string) ([]Comment, error)
	GetListByBoardIdAndTitle(ctx context.Context, arg GetListByBoardIdAndTitleParams) (GetListByBoardIdAndTitleRow, error)
	GetListsByBoardId(ctx context.Context, boardID string) ([]GetListsByBoardIdRow, error)
	GetMaxPositionInList(ctx context.Context, listID string) (int64, error)
	GetTags(ctx context.Context) ([]GetTagsRow, error)
	GetTagsByCardIds(ctx context.Context, cardIds []string) ([]GetTagsByCardIdsRow, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateCard(ctx context.Context, arg UpdateCardParams) error
	UpdateCardList(ctx context.Context, arg UpdateCardListParams) error
	UpdateCardPosition(ctx context.Context, arg UpdateCardPositionParams) error
}

var _ Querier = (*Queries)(nil)
