root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"
cmd = "go build -o tmp/main ./cmd"
include_ext = ["go", "sql"]
exclude_dir = ["tmp"]
delay = 1000

[log]
time = false

[screen]
clear_on_rebuild = true
