version: '3'

interval: 100ms

vars:
  TAILWIND_VERSION: v4.1.16
  tailwind_bin:
    sh: |
      if [ "$OS" = "Windows_NT" ]; then
        echo "./bin/tailwindcss.exe"
      else
        echo "./bin/tailwindcss"
      fi

tasks:
  tailwindcss:install:
    generates:
      - bin/tailwindcss
      - bin/tailwindcss.exe
    status:
      - sh -c '[ -f bin/tailwindcss ] || [ -f bin/tailwindcss.exe ]'
    cmds:
      - |
        set -e
        VERSION="{{.TAILWIND_VERSION}}"
        mkdir -p bin
        if [ "$OS" = "Windows_NT" ]; then
          FILE="tailwindcss-windows-x64.exe"
          DEST="bin/tailwindcss.exe"
        else
          UNAME="$(uname -s)"
          ARCH="$(uname -m)"
          case "$UNAME" in
            Darwin)
              if [ "$ARCH" = "arm64" ] || [ "$ARCH" = "aarch64" ]; then
                FILE="tailwindcss-macos-arm64"
              else
                FILE="tailwindcss-macos-x64"
              fi
              DEST="bin/tailwindcss"
              ;;
            Linux)
              case "$ARCH" in
                x86_64|amd64) FILE="tailwindcss-linux-x64" ;;
                arm64|aarch64) FILE="tailwindcss-linux-arm64" ;;
                *)
                  echo "Unsupported architecture: $ARCH"
                  exit 1
                  ;;
              esac
              DEST="bin/tailwindcss"
              ;;
            *)
              echo "Unsupported platform: $UNAME"
              exit 1
              ;;
          esac
        fi
        URL="https://github.com/tailwindlabs/tailwindcss/releases/download/${VERSION}/${FILE}"
        echo "Downloading Tailwind CSS CLI ${VERSION} (${FILE})"
        if command -v curl >/dev/null 2>&1; then
          curl -sSL "$URL" -o "${DEST}.tmp"
        elif command -v wget >/dev/null 2>&1; then
          wget -qO "${DEST}.tmp" "$URL"
        else
          echo "Neither curl nor wget is available to download Tailwind CSS."
          exit 1
        fi
        mv "${DEST}.tmp" "${DEST}"
        if [ "$OS" != "Windows_NT" ]; then
          chmod +x "${DEST}"
        fi

  css:
    deps: 
      - tailwindcss:install
    sources:
      - ./web/input.css
    generates:
      - ./web/static/style.css
    cmd: "{{.tailwind_bin}} -i ./web/input.css -o ./web/static/style.css"

  templ:
    sources:
      - ./**/*.templ
    generates:
      - ./**/*_templ.go
    cmd: go tool templ generate

  sqlc:
    desc: Generate sqlc query helpers
    dir: sql
    sources:
      - ./**/*.sql
    generates:
      - zz/*.go
    cmds:
      - go tool sqlc generate

  site:
    method: none
    sources: 
      - ./**/*.go
      - exclude: ./**/*_templ.go
    deps: 
      - templ
      - css
      - sqlc
    cmds:
      - go mod tidy
      - go build -o bin/kanban-datastar cmd/main.go 
      - ./bin/kanban-datastar

  default:
    deps:
      - site